const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
class Node{constructor(){this.children=[];this.hidden=false;this.attrs={}}append(n){this.children.push(n)}insertBefore(n,target){this.children.splice(this.children.indexOf(target),0,n)}replaceChildren(){this.children=[]}setAttribute(k,v){this.attrs[k]=v}set innerHTML(v){throw Error('unsafe HTML')}}
const nodes=new Map(),messages=[],listeners={},storage=new Map(),timers=new Map();let timerId=0,poll;
const document={hidden:false,documentElement:{scrollHeight:250,style:{}},getElementById(id){if(!nodes.has(id))nodes.set(id,new Node());return nodes.get(id)},createElement(){return new Node()}};
const data={sessions:[{chat_name:'<img onerror=alert(1)>',status:'running',usage:{new_input_tokens:10,cached_input_tokens:20,output_tokens:3},credit_coverage_complete:false,credit_priced_calls:1,known_estimated_credits:'2.5',missing_usage_turns:1}],account_usage:{stale:true,limits:[{limit_id:'codex',label:'5h',used_percent:40}]},updated_at:'2026-10-03T00:00:00Z'};
const parent={postMessage(m){messages.push(m);if(m.id)setImmediate(()=>listeners.message({source:parent,data:{jsonrpc:'2.0',id:m.id,result:m.method==='ui/initialize'?{hostContext:{theme:'dark'}}:{structuredContent:data}}}))}};
const window={parent,addEventListener(type,fn){listeners[type]=fn}};
const ctx=vm.createContext({document,window,location:{pathname:'/mcp-ui'},localStorage:{getItem:k=>storage.get(k),setItem:(k,v)=>storage.set(k,v)},setTimeout(fn){timers.set(++timerId,fn);return timerId},clearTimeout(id){timers.delete(id)},setInterval(fn,ms){assert.equal(ms,5000);poll=fn}});
const html=fs.readFileSync('src/token_budget_mcp/usage_panel.html','utf8');
(async()=>{vm.runInContext(html.match(/<script>([\s\S]*?)<\/script>/)[1],ctx);await new Promise(r=>setTimeout(r,30));assert.equal(nodes.get('heading').textContent,'CUT · 5h 40% used (stale)');const row=nodes.get('rows').children[0];assert.equal(row.children[0].textContent,data.sessions[0].chat_name);assert.match(row.children[2].textContent,/partial/);assert.match(row.children[1].textContent,/Credits ≈2.50 · partial/);nodes.get('collapse').onclick();assert(nodes.get('body').hidden);assert.equal(storage.get('cut-inline-collapsed'),'true');assert.equal(nodes.get('collapse').attrs['aria-expanded'],'false');let count=messages.length;document.hidden=true;await poll();assert.equal(messages.length,count);document.hidden=false;await poll();await new Promise(r=>setTimeout(r,10));assert(messages.filter(m=>m.method==='tools/call').length>=2);const original=nodes.get('heading').textContent;listeners.message({source:{},data:{jsonrpc:'2.0',method:'ui/notifications/tool-result',params:{structuredContent:{sessions:[],account_usage:null}}}});assert.equal(nodes.get('heading').textContent,original);let fail=false,fetchCount=0;const local=vm.createContext({document,window,location:{pathname:'/panel'},AbortController,localStorage:{getItem:()=>null,setItem:()=>{}},setTimeout,clearTimeout,setInterval(fn){poll=fn},async fetch(url){assert.equal(url,'/api/turns');fetchCount++;return {ok:!fail,json:async()=>({...data,floating_sessions:[...data.sessions,{is_internal:true,chat_name:'internal'}]})}}});vm.runInContext(html.match(/<script>([\s\S]*?)<\/script>/)[1],local);await new Promise(r=>setTimeout(r,10));assert.equal(fetchCount,1);assert.equal(nodes.get('rows').children.length,1);fail=true;await poll();assert.match(nodes.get('heading').textContent,/offline/);assert.match(nodes.get('error').textContent,/Last reading retained/);fail=false;await poll();assert.equal(nodes.get('error').textContent,'');assert(!nodes.get('heading').textContent.includes('offline'));console.log('PASS: local collector transport, HTTP failure/recovery, initialization, safe text, partial/stale values, collapse persistence, live polling and hidden-view pause')})().catch(e=>{console.error(e);process.exitCode=1});
